"use client";

import { useMemo, useState } from "react";
import { Stock } from "@/lib/types";
import PulseGrid from "./PulseGrid";
import HeroSearch from "./HeroSearch";
import TickerMarquee from "./TickerMarquee";
import StockGrid from "./StockGrid";
import { Brain, ShieldCheck, TrendingUp } from "lucide-react";

export default function HomeClient({ stocks }: { stocks: Stock[] }) {
  const [query, setQuery] = useState("");

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return stocks;
    return stocks.filter(
      (s) =>
        s.symbol.toLowerCase().includes(q) ||
        s.name.toLowerCase().includes(q) ||
        s.sector.toLowerCase().includes(q)
    );
  }, [stocks, query]);

  return (
    <>
      <section className="relative flex min-h-screen flex-col items-center justify-center overflow-hidden px-5 pt-16">
        <PulseGrid />

        <div className="relative z-10 flex w-full flex-col items-center animate-fade-in">
          <span className="label-eyebrow glass-pill mb-6 px-4 py-1.5">
            Predictive intelligence \u00b7 200+ equities tracked
          </span>
          <h1 className="max-w-3xl text-center font-display text-4xl font-semibold leading-[1.1] tracking-tight text-ink sm:text-6xl">
            Read the market&rsquo;s
            <span className="bg-gradient-to-r from-aqua to-violet bg-clip-text text-transparent">
              {" "}
              next move
            </span>
            , not just its past.
          </h1>
          <p className="mt-5 max-w-xl text-center text-base text-ink-muted sm:text-lg">
            Astock pairs machine-learning return forecasts with transparent risk
            scoring, so you can search any ticker and see what&rsquo;s ahead.
          </p>

          <div className="mt-10 w-full">
            <HeroSearch stocks={stocks} query={query} onQueryChange={setQuery} />
            <TickerMarquee stocks={stocks} />
          </div>
        </div>

        <div className="pointer-events-none absolute bottom-8 left-1/2 z-10 -translate-x-1/2 animate-pulse-soft text-[11px] tracking-[0.3em] text-ink-faint">
          SCROLL TO EXPLORE
        </div>
      </section>

      <section id="how-it-works" className="mx-auto max-w-6xl px-5 py-16 sm:px-8">
        <div className="grid grid-cols-1 gap-5 sm:grid-cols-3">
          {[
            {
              icon: TrendingUp,
              title: "Forecasted returns",
              copy: "A 12-month expected return derived from historical price behavior and fundamentals.",
            },
            {
              icon: ShieldCheck,
              title: "Risk scoring",
              copy: "Every ticker gets a 1\u201310 risk score so upside is always weighed against volatility.",
            },
            {
              icon: Brain,
              title: "Model-backed",
              copy: "Predictions are generated by Astock's ML pipeline, refreshed as new data arrives.",
            },
          ].map(({ icon: Icon, title, copy }) => (
            <div key={title} className="glass-panel rounded-2xl p-6">
              <Icon className="text-aqua" size={22} />
              <h3 className="mt-4 font-display text-lg font-medium text-ink">{title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-ink-muted">{copy}</p>
            </div>
          ))}
        </div>
      </section>

      <section id="discover" className="mx-auto max-w-7xl px-5 pb-24 sm:px-8">
        <div className="mb-8 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <p className="label-eyebrow mb-2">Discovery grid</p>
            <h2 className="font-display text-2xl font-semibold text-ink sm:text-3xl">
              {query ? `Results for \u201c${query}\u201d` : "All tracked equities"}
            </h2>
          </div>
          <p className="font-mono text-sm text-ink-faint">{filtered.length} of {stocks.length} shown</p>
        </div>

        <StockGrid stocks={filtered} query={query} />
      </section>
    </>
  );
}
